Cambiamenti
===========

Changelog completo:
https://github.com/NethServer/dev/milestone/5?closed=1

Bugs conosciuti:
https://github.com/NethServer/dev/issues?q=is%3Aissue+is%3Aopen+label%3Abug


Pacchetti rimossi
-----------------

I seguenti pacchetti sono stati rimossi:

* nethserver-collectd-web: sostituito con nethserver-cgp
* nethserver-password: integrato in nethserver-sssd
* nethserver-faxweb2: http://community.nethserver.org/t/ns-7-faxweb2-vs-avantafax/2645
* nethserver-fetchmail: sostituito con getmail
* nethserver-ocsinventory, nethserver-adagios: a causa di problemi di compatibilità con Nagios, questi moduli verranno supportati solo su |product| 6.x
