Cambiamenti
===========

* NethForge è ora installata e abilitata di default
* Aggiornamenti da CentOS 6.8
* La policy di SELinux è cambiata da ``permissive`` a ``disabled``
* Il pacchetto ``collectd`` è stato aggiornato dalla versione 4 alla 5
* Elenco completo degli `aggiornamenti alla 6.8`_
* Elenco completo delle `migliorie della release 6.7`_
  

.. _`aggiornamenti alla 6.8`: http://dev.nethserver.org/projects/nethserver/issues?query_id=65
.. _`migliorie della release 6.7`: http://dev.nethserver.org/projects/nethserver/issues?query_id=64