#!/bin/bash

BASE_URL=https://raw.githubusercontent.com/NethServer

branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
branch_name=${branch_name:-HEAD}
branch_name=${branch_name:0:2} # truncate branch name to 2 chars, eg: v7a -> v7

echo "Remember to commit the following files:"
echo
for r in `cat modules`
do
    curl -sf $BASE_URL/$r/$branch_name/README.rst -o $r.rst
    if [[ $? != 0 ]]; then # link not valid, try with master branch
        curl -sf $BASE_URL/$r/master/README.rst -o $r.rst
        if [[ $? == 0 ]]; then
            echo "         $r.rst (master)"
        else
            echo "    !ERR $r.rst $BASE_URL/$r/master/README.rst"
        fi
        continue
    fi

    if [[ $? == 0 ]]; then
        echo "         $r.rst"
    else
        echo "    !ERR $r.rst $BASE_URL/$r/$branch_name/README.rst"
    fi
done
echo
